# Generated by Django 2.1 on 2019-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mementoitem',
            name='blurb',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
    ]
