# Generated by Django 2.1 on 2019-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0002_mementoitem_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mementoitem',
            name='blurb',
            field=models.TextField(blank=True, default='blurb', null=True),
        ),
        migrations.AlterField(
            model_name='mementoitem',
            name='link',
            field=models.TextField(blank=True, default='link', null=True),
        ),
        migrations.AlterField(
            model_name='mementoitem',
            name='note',
            field=models.TextField(blank=True, default='note', null=True),
        ),
        migrations.AlterField(
            model_name='mementoitem',
            name='title',
            field=models.TextField(blank=True, default='title', null=True),
        ),
    ]
