# Generated by Django 2.1 on 2019-08-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0003_auto_20190827_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mementoitem',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mementoitem',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mementoitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mementoitem',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
